substitutions:
  _ENV:


# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/321ignition-backend:$SHORT_SHA', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/321ignition-backend:$SHORT_SHA']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - set
#   - image
#   - deployment
#   - api-321ignition-deployment
#   - api-321ignition=gcr.io/$PROJECT_ID/321ignition-backend:$SHORT_SHA
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=api-321ignition-cluster'


steps:
# Install dependencies 
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

#  build project
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '${_ENV}' , '$TAG_NAME']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'webpack_prod']

# create  deploy
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'generate_yaml', '$TAG_NAME']

## Deploy app
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--quiet"]
